Repository cherrypy/cheroot, pull requests merged in 2020-07, with the labels that each got.

#303 Use Python 3.8 for linting jobs in Zuul CI
  .zuul.yaml
Labels: bug, regression

#301 Use selectors lib to address select() fd num limit
  cheroot/_compat.py
  cheroot/connections.py
  cheroot/test/test_server.py
  docs/spelling_wordlist.txt
  setup.cfg
Labels: Linux, bug, enhancement, help wanted, regression, reproducer: present

#306 Fix ConnectionAbortedError in builtin ssl WSGI environment setup
  cheroot/ssl/builtin.py
  cheroot/test/test_ssl.py
Labels: Windows, bug, enhancement
